version: '3'

services:
    db:
        image: postgres:11
        container_name: transcendence_db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:${DB_PORT}