version: '3'

services:
    db:
        image: postgres:11
        container_name: transcendence_db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - 5432:${DB_PORT}
        networks:
            - transcendence 

    front:
        build: ./transcendence-front
        image: transcendence_front 
        container_name: transcendence_front
        restart: unless-stopped
        depends_on:
            - back
        env_file:
            - .env
        environment:
            - PORT=3000
        ports:
            - 3000:3000
        networks:
            - transcendence 

    back:
        build: ./transcendence-back
        image: transcendence_back 
        container_name: transcendence_back
        restart: unless-stopped
        depends_on:
            - db
        env_file:
            - .env
        environment:
            - DB_HOST=transcendence_db
        ports:
            - 4444:4444
        networks:
            - transcendence 

networks:
    transcendence:
        driver: bridge